config/routes.rb
Rails.application.routes.draw do
  resources :gardens do
    resources :plants, only: [:create]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :plants, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/garden.rb
class Garden < ApplicationRecord
  validates :name, presence: true
  has_many :plants
end

app/models/plant.rb
class Plant < ApplicationRecord
  belongs_to :garden
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/gardens_controller.rb
class GardensController < ApplicationController
  before_action :set_garden, only: %i[ show edit update destroy ]

  # GET /gardens or /gardens.json
  def index
    @gardens = Garden.all
  end

  # GET /gardens/1 or /gardens/1.json
  def show
  end

  # GET /gardens/new
  def new
    @garden = Garden.new
  end

  # GET /gardens/1/edit
  def edit
  end

  # POST /gardens or /gardens.json
  def create
    @garden = Garden.new(garden_params)

    respond_to do |format|
      if @garden.save
        format.html { redirect_to garden_url(@garden), notice: "Garden was successfully created." }
        format.json { render :show, status: :created, location: @garden }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @garden.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gardens/1 or /gardens/1.json
  def update
    respond_to do |format|
      if @garden.update(garden_params)
        format.html { redirect_to garden_url(@garden), notice: "Garden was successfully updated." }
        format.json { render :show, status: :ok, location: @garden }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @garden.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gardens/1 or /gardens/1.json
  def destroy
    @garden.destroy

    respond_to do |format|
      format.html { redirect_to gardens_url, notice: "Garden was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_garden
      @garden = Garden.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def garden_params
      params.require(:garden).permit(:name, :banner_url)
    end
end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController

  def create
    @garden = Garden.find(params[:garden_id])
    @plant = Plant.new(plant_params)
    @plant.garden = @garden
    if @plant.save
      redirect_to garden_path(@garden)
    else
      render :new
    end
  end

  def destroy
  @plant = Plant.find(params[:id])
  @plant.destroy
  redirect_to garden_path(@plant.garden)
  end

  private

  def plant_params
  params.require(:plant).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gardens_helper.rb
module GardensHelper
end

app/helpers/plants_helper.rb
module PlantsHelper
end

app/views/gardens/_form.html.erb
<%= simple_form_for(@garden) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :banner_url %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/gardens/edit.html.erb
<h1>Editing Garden</h1>

<%= render 'form', garden: @garden %>

<%= link_to 'Show', @garden %> |
<%= link_to 'Back', gardens_path %>

app/views/gardens/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Gardens</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Banner url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @gardens.each do |garden| %>
      <tr>
        <td><%= garden.name %></td>
        <%= image_tag garden.banner_url %>
        <td><%= link_to 'Show', garden %></td>
        <td><%= link_to 'Edit', edit_garden_path(garden) %></td>
        <td><%= link_to 'Destroy', garden, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Garden', new_garden_path %>

app/views/gardens/new.html.erb
<h1>New Garden</h1>

<%= render 'form', garden: @garden %>

<%= link_to 'Back', gardens_path %>

app/views/gardens/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @garden.name %>
</p>

<p>
  <strong>Banner url:</strong>
  <%= @garden.banner_url %>
</p>

<ul>
<% @garden.plants.each do |plant| %>
  <li> <%= plant.name %></li>
<%= link_to 'destroy', plant_path(plant), method: :delete %>
<% end  %>
</ul>

<%= link_to 'Edit', edit_garden_path(@garden) %>
<%= link_to 'Back', gardens_path %>

<%= render "plants/form"  %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GardensAndPlants</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/plants/_form.html.erb
<%= simple_form_for [@garden,Plant.new] do |f| %>
  <%=f.input :name  %>
  <%= f.button :submit %>
<%end  %>

app/views/plants/new.html.erb
<h1>VIENS CREER TA PLANTE</h1>

<%= render "plants/form"  %>